#FROM node:18-alpine

#WORKDIR /app

#COPY package* .

#RUN npm install

#COPY . .

#CMD [ "npm", "run", "dev" ]

FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

CMD [ "npm", "run", "dev" ]
