import {
  CircleStackIcon,
  ClipboardDocumentIcon,
  HomeIcon,
  PresentationChartBarIcon,
  TableCellsIcon,
  Cog6ToothIcon,
  AdjustmentsHorizontalIcon,
  BookOpenIcon,
  UserGroupIcon,
  ArrowLeftCircleIcon,
  ArrowDownTrayIcon,
  BackspaceIcon,
  ArrowTopRightOnSquareIcon,
  BuildingStorefrontIcon,
  ChartBarIcon,
  CameraIcon,
  ChartPieIcon,
  CalendarIcon,
  BoltIcon,
  ClockIcon,
  Cog8ToothIcon,
  CreditCardIcon,
  CloudIcon,
  EllipsisHorizontalIcon,
  FolderOpenIcon,
  UserIcon,
  CalendarDaysIcon,
  ArchiveBoxIcon,
  UserPlusIcon,
  UsersIcon
} from '@heroicons/react/24/outline'

export const ICON = {
  HomeIcon: <HomeIcon className="w-5 h-5" />,
  CircleStack: <CircleStackIcon className="w-5 h-5" />,
  ClipboardDocumentIcon: <ClipboardDocumentIcon className="w-5 h-5" />,
  TableCells: <TableCellsIcon className="w-5 h-5" />,
  PresentationChartBar: <PresentationChartBarIcon className="w-5 h-5" />,
  Cog6Tooth: <Cog6ToothIcon className="w-5 h-5" />,
  AdjustmentsHorizontal: <AdjustmentsHorizontalIcon className="w-5 h-5" />,
  BookOpenIcon: <BookOpenIcon className="w-5 h-5" />,
  UserGroup: <UserGroupIcon className="w-5 h-5" />,
  ArrowLeftCircle: <ArrowLeftCircleIcon className="w-5 h-5" />,
  ArrowDownTray: <ArrowDownTrayIcon className="w-5 h-5" />,
  Backspace: <BackspaceIcon className="w-5 h-5" />,
  ArrowTopRightOnSquare: <ArrowTopRightOnSquareIcon className="w-5 h-5" />,
  BuildingStorefront: <BuildingStorefrontIcon className="w-5 h-5" />,
  ChartBar: <ChartBarIcon className="w-5 h-5" />,
  Camera: <CameraIcon className="w-5 h-5" />,
  ChartPie: <ChartPieIcon className="w-5 h-5" />,
  Calendar: <CalendarIcon className="w-5 h-5" />,
  Bolt: <BoltIcon className="w-5 h-5" />,
  Clock: <ClockIcon className="w-5 h-5" />,
  Cog8Tooth: <Cog8ToothIcon className="w-5 h-5" />,
  CreditCard: <CreditCardIcon className="w-5 h-5" />,
  Cloud: <CloudIcon className="w-5 h-5" />,
  EllipsisHorizontal: <EllipsisHorizontalIcon className="w-5 h-5" />,
  FolderOpen: <FolderOpenIcon className="w-5 h-5" />,
  UserIcon: <UserIcon className="w-5 h-5" />,
  CalendarDaysIcon: <CalendarDaysIcon className="w-5 h-5" />,
  RoomIcon: <img src='/room.svg' alt="room" className="w-5 h-5" />,
  ArchiveBoxIcon: <ArchiveBoxIcon className="w-5 h-5" />,
  UserPlusIcon: <UserPlusIcon className="w-5 h-5" />,
  UsersIcon: <UsersIcon className="w-5 h-5" />
}
